# Generated by Django 6.0.5 on 2026-05-28 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qampus', '0003_post_likes_post_scraps_comment_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['created_at']},
        ),
    ]
