# Generated by Django 6.0.5 on 2026-05-28 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qampus', '0007_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
