# Generated by Django 6.0.5 on 2026-05-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qampus', '0008_remove_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='scraps',
        ),
        migrations.AddField(
            model_name='post',
            name='scrap_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
